apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: issuegen-rollouts
spec:
  destination:
    namespace: maheshprom
    server: https://kubernetes.default.svc
  project: default
  source:
    path: issuegen
    repoURL: https://github.com/maheshopsmx/argocd-example-apps.git
    targetRevision: HEAD
