apiVersion: v1
kind: ConfigMap
metadata:
  name: issuegen-metrics
data:
  providerConfig: |
    application: issuegen-rollouts
    lifetimeMinutes: 3
    gitops: false
    passScore: 90
    serviceList: 
    - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "maheshdata1,.*{{env.STABLE_POD_HASH}}.*,issuegen-app"
      canaryMetricScope: "maheshdata1,.*{{env.LATEST_POD_HASH}}.*,issuegen-app"
      metricTemplateName: "opsmx-metrictemplate"
      serviceName: service1
