apiVersion: v1
kind: ConfigMap
metadata:
  name: issuegen-metrics
data:
  providerConfig: |
    application: issuegen-rollouts
    lifetimeMinutes: 3
    gitops: false
    passScore: 90
    serviceList: 
    - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "isg-argofull,.*{{env.STABLE_POD_HASH}}.*,nginx"
      canaryMetricScope: "isg-argofull,.*{{env.LATEST_POD_HASH}}.*,nginx"
      metricTemplateName: "prommetric"
      serviceName: service1
