apiVersion: argoproj.io/v1alpha1 # Create a rollout resource
kind: Rollout
metadata:
  name: issuegen-rollout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issuegen-app
  workloadRef: # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: issuegen-deployment
  strategy:
    blueGreen:
      autoPromotionEnabled: true
      activeService: issuegen-app-stable
      previewService: issuegen-app-preview
      prePromotionAnalysis:
        templates:
          - templateName: issuegen-template
        args:
          - name: baseline-hash
            valueFrom:
              podTemplateHashValue: Stable
          - name: preview-hash
            valueFrom:
              podTemplateHashValue: Latest
          - name: servicename
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
