apiVersion: v1
kind: ConfigMap
metadata:
  name: details
data:
  providerConfig: |
    application: bookinfo-rollout
    user: admin
    lifetimeMinutes: 12
    gitops: true
    passScore: 90
    serviceList: 
    - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "maheshprom,.*{{env.STABLE_POD_HASH}}.*,details"
      canaryMetricScope: "maheshprom,.*{{env.LATEST_POD_HASH}}.*,details"
      metricTemplateName: "metrixtemplates"
      serviceName: details
