apiVersion: argoproj.io/v1alpha1 # Create a rollout resource
kind: Rollout
metadata:
  name: guestbook-rollout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  workloadRef: # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: guestbook-ui
  strategy:
    blueGreen:
      autoPromotionEnabled: true
      activeService: guestbook-ui-stable
      previewService: guestbook-ui-preview
      prePromotionAnalysis:
        templates:
          - templateName: guestbook-template
        args:
          - name: baseline-hash
            valueFrom:
              podTemplateHashValue: Stable
          - name: preview-hash
            valueFrom:
              podTemplateHashValue: Latest
          - name: servicename
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
