apiVersion: batch/v1
kind: Job
metadata:
  name: mahesh-job
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  template:
    spec:
      containers:
      - command: ["sleep", "20"]
        image: quay.io/argoproj/argocd:v2.5.3
        imagePullPolicy: IfNotPresent
        name: maheshjob
      restartPolicy: OnFailure
