apiVersion: v1
stringData:
  cd-integration: "truebbb"
  gate-url: "https://isddata.argo.ninja-test.opsmx.org"
  source-name: argocd
  user: admin
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
  name: opsmx-profilei
